// The MIT License
// 
// Copyright (c) 2012 Gwendal Roué
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.






/*
 * Set up standard GRMustache versions
 */
#define GRMUSTACHE_VERSION_1_0  1000
#define GRMUSTACHE_VERSION_1_1  1010
#define GRMUSTACHE_VERSION_1_2  1020
#define GRMUSTACHE_VERSION_1_3  1030
#define GRMUSTACHE_VERSION_1_4  1040
#define GRMUSTACHE_VERSION_1_5  1050
#define GRMUSTACHE_VERSION_1_6  1060
#define GRMUSTACHE_VERSION_1_7  1070
#define GRMUSTACHE_VERSION_1_8  1080
#define GRMUSTACHE_VERSION_1_9  1090
#define GRMUSTACHE_VERSION_1_10 1100
#define GRMUSTACHE_VERSION_1_11 1110
#define GRMUSTACHE_VERSION_1_12 1120
#define GRMUSTACHE_VERSION_1_13 1130






/* 
 * If max GRMustacheVersion not specified, assume 1.13
 */
#ifndef GRMUSTACHE_VERSION_MAX_ALLOWED
#define GRMUSTACHE_VERSION_MAX_ALLOWED    GRMUSTACHE_VERSION_1_13
#endif

/*
 * if min GRMustacheVersion not specified, assume max
 */
#ifndef GRMUSTACHE_VERSION_MIN_REQUIRED
#define GRMUSTACHE_VERSION_MIN_REQUIRED    GRMUSTACHE_VERSION_MAX_ALLOWED
#endif

/*
 * Error on bad values
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_MIN_REQUIRED
#error GRMUSTACHE_VERSION_MAX_ALLOWED must be >= GRMUSTACHE_VERSION_MIN_REQUIRED
#endif
#if GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_0
#error GRMUSTACHE_VERSION_MIN_REQUIRED must be >= GRMUSTACHE_VERSION_1_0
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.0
 */
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.0, 
 * and deprecated in GRMustache 1.0
 */
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_0_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.0
 */
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_0_AND_LATER    DEPRECATED_ATTRIBUTE






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.1
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_1
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_1
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * and deprecated in GRMustache 1.1
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_1
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_1
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.1
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_1
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_1    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_1    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_1_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.1
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_1
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_1_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.2
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_2
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_2
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * and deprecated in GRMustache 1.2
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_2
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_2
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.2
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_2
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_2    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_2    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_2
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.2
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_2
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_2    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_2    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_2_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.2
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_2
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_2_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.3
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_3
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_3
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * and deprecated in GRMustache 1.3
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_3
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.3
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_3
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.3
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_3
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.3
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_3
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_3    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_3_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.3
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_3
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_3_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * and deprecated in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_4
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_4    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_4_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.4
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_4
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_4_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * and deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_5    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_5_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.5
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_5
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_5_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * and deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_6    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_6_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.6
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_6
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_6_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * and deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_7    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_7_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.7
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_7
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_7_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.8,
 * and deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * but later deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_8    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_8_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.8
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_8
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_8_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.9,
 * and deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9
 * 
 * Used on declarations introduced in GRMustache 1.8,
 * but later deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_9    AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_9_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.9
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_9
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_9_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.10,
 * and deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.8,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10
 * 
 * Used on declarations introduced in GRMustache 1.9,
 * but later deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_10    AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_10_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.10
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_10
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_10_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_10_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.11,
 * and deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.8,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.9,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11
 * 
 * Used on declarations introduced in GRMustache 1.10,
 * but later deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_11    AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_11_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.11
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_11
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_11_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_11_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.12,
 * and deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.8,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.9,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.10,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12
 * 
 * Used on declarations introduced in GRMustache 1.11,
 * but later deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_12    AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_12_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.12
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_12
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_12_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_12_AND_LATER
#endif






/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER
 * 
 * Used on declarations introduced in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MAX_ALLOWED < GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER    UNAVAILABLE_ATTRIBUTE
#elif GRMUSTACHE_VERSION_MIN_REQUIRED < GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER    WEAK_IMPORT_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER_BUT_DEPRECATED
 * 
 * Used on declarations introduced in GRMustache 1.13,
 * and deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER_BUT_DEPRECATED    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER_BUT_DEPRECATED    AVAILABLE_GRMUSTACHE_VERSION_1_13_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.0,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_0_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.1,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_1_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.2,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_2_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.3,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_3_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.4,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_4_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.5,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_5_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.6,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_6_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.7,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_7_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.8,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_8_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.9,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_9_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.10,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_10_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.11,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_11_AND_LATER
#endif

/*
 * AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13
 * 
 * Used on declarations introduced in GRMustache 1.12,
 * but later deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    DEPRECATED_ATTRIBUTE
#else
#define AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER_BUT_DEPRECATED_IN_GRMUSTACHE_VERSION_1_13    AVAILABLE_GRMUSTACHE_VERSION_1_12_AND_LATER
#endif

/*
 * DEPRECATED_IN_GRMUSTACHE_VERSION_1_13_AND_LATER
 * 
 * Used on types deprecated in GRMustache 1.13
 */
#if GRMUSTACHE_VERSION_MIN_REQUIRED >= GRMUSTACHE_VERSION_1_13
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_13_AND_LATER    DEPRECATED_ATTRIBUTE
#else
#define DEPRECATED_IN_GRMUSTACHE_VERSION_1_13_AND_LATER
#endif






